build: homework
	javac homework/*.java
	jar cf tema1.jar homework/*.class

run-p1:     
	java -classpath ./tema1.jar homework.Crypto
run-p2:      
	java -classpath ./tema1.jar homework.Stocks
run-p3:      
	java -classpath ./tema1.jar homework.Valley
run-p4:      
	java -classpath ./tema1.jar homework.Ridge
	
clean:	
	rm homework/*.class
	rm tema1.jar	 
